version: "3.6"

services:
  api:
    container_name: millioner-api
    build: ./
    environment:
      - MONGO_URI=mongodb://millioner-db/Quiz
      - JWT_SECRET=12345678
    ports:
      - "3000:3000"
    links:
      - millioner-db

  
  millioner-db:
    container_name: millioner-db
    image: mongo
    ports:
      - "27017:27017"


  mongo_seed:
    build: ./db-seed
    ports:
      - "9000:27017"
    links:
      - millioner-db