version: "3.6"

services:
  api:
    container_name: millioner-api
    build: ./
    command: npm run start:dev
    environment:
      - MONGO_URI=mongodb://millioner-db/Quiz
      - JWT_SECRET=12345678
      - REDIS_URI=redis://redis:6379
    ports:
      - "3000:3000"
    links:
      - millioner-db
      - redis
    volumes:
      - .:/usr/src/millioner-api/
      - /usr/src/millioner-api/node_modules

  millioner-db:
    container_name: millioner-db
    image: mongo
    ports:
      - "27017:27017"

  mongo_seed:
    build: ./db-seed
    ports:
      - "9000:27017"
    links:
      - millioner-db

  redis:
    image: redis
    ports:
      - "6379:6379"
